name: GitHub Actions Demo
run-name: incoming request
on:
  workflow_dispatch:
    inputs:
      incomingRequest:
        description: "request payload"
jobs:
  web-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: node github-actions-gateway.mjs
